apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-assistant
  labels:
    app: product-assistant
spec:
# we are running 2 replicas (2 ports) (we moved to 1 because of the memory constraints)
  # replicas: 2
  replicas: 1
  selector:
    matchLabels:
      app: product-assistant
  template:
    metadata:
      labels:
        app: product-assistant
    spec:
      containers:
      - name: product-assistant
        image: 326541255324.dkr.ecr.eu-north-1.amazonaws.com/product-assistant:latest
        ports:
        - containerPort: 8000
        resources: 
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:                              
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: GOOGLE_API_KEY
        - name: ASTRA_DB_API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_API_ENDPOINT
        - name: ASTRA_DB_APPLICATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_APPLICATION_TOKEN
        - name: ASTRA_DB_KEYSPACE
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_KEYSPACE